// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateChat(arg1:string):Promise<main.ChatInfo>;

export function DeleteChat(arg1:string):Promise<void>;

export function ExecuteCommand(arg1:string,arg2:boolean):Promise<string>;

export function GetActiveChat():Promise<main.ChatInfo>;

export function GetChatMessages(arg1:string):Promise<Array<main.MessageInfo>>;

export function GetChats():Promise<Array<main.ChatInfo>>;

export function Greet(arg1:string):Promise<string>;

export function InitDatabase():Promise<void>;

export function PreviewCommand(arg1:string):Promise<main.CommandPreview>;

export function RunCommand(arg1:string):Promise<string>;

export function SaveMessage(arg1:string,arg2:string,arg3:string):Promise<main.MessageInfo>;

export function UpdateChatTitle(arg1:string,arg2:string):Promise<void>;
