// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ActivateMode(arg1:string):Promise<string>;

export function CreateChat(arg1:string):Promise<main.ChatInfo>;

export function CreateMode(arg1:string,arg2:string,arg3:number,arg4:boolean,arg5:string,arg6:string,arg7:string):Promise<string>;

export function DeactivateMode(arg1:string):Promise<void>;

export function DeleteChat(arg1:string):Promise<void>;

export function DeleteMode(arg1:string):Promise<void>;

export function ExecuteCommand(arg1:string,arg2:boolean):Promise<string>;

export function GetActiveChat():Promise<main.ChatInfo>;

export function GetActiveSession():Promise<string>;

export function GetChatMessages(arg1:string):Promise<Array<main.MessageInfo>>;

export function GetChats():Promise<Array<main.ChatInfo>>;

export function GetInstalledApps():Promise<string>;

export function GetSessionFiles(arg1:string):Promise<string>;

export function GetSessionInfo(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function InitDatabase():Promise<void>;

export function ListModes():Promise<string>;

export function PreviewCommand(arg1:string):Promise<main.CommandPreview>;

export function RunCommand(arg1:string):Promise<string>;

export function SaveMessage(arg1:string,arg2:string,arg3:string):Promise<main.MessageInfo>;

export function ToggleMode(arg1:string,arg2:boolean):Promise<void>;

export function UpdateChatTitle(arg1:string,arg2:string):Promise<void>;

export function UpdateMode(arg1:string,arg2:string,arg3:string,arg4:number,arg5:boolean,arg6:boolean,arg7:string,arg8:string,arg9:string):Promise<string>;
