// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateMode(arg1) {
  return window['go']['main']['App']['ActivateMode'](arg1);
}

export function AddAllowedApp(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddAllowedApp'](arg1, arg2, arg3, arg4, arg5);
}

export function CheckAppOnPC(arg1) {
  return window['go']['main']['App']['CheckAppOnPC'](arg1);
}

export function CreateChat(arg1) {
  return window['go']['main']['App']['CreateChat'](arg1);
}

export function CreateMode(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['CreateMode'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function DeactivateMode(arg1) {
  return window['go']['main']['App']['DeactivateMode'](arg1);
}

export function DeleteChat(arg1) {
  return window['go']['main']['App']['DeleteChat'](arg1);
}

export function DeleteMode(arg1) {
  return window['go']['main']['App']['DeleteMode'](arg1);
}

export function ExecuteCommand(arg1, arg2) {
  return window['go']['main']['App']['ExecuteCommand'](arg1, arg2);
}

export function GetActiveChat() {
  return window['go']['main']['App']['GetActiveChat']();
}

export function GetActiveSession() {
  return window['go']['main']['App']['GetActiveSession']();
}

export function GetAllDetectableApps() {
  return window['go']['main']['App']['GetAllDetectableApps']();
}

export function GetChatMessages(arg1) {
  return window['go']['main']['App']['GetChatMessages'](arg1);
}

export function GetChats() {
  return window['go']['main']['App']['GetChats']();
}

export function GetInstalledApps() {
  return window['go']['main']['App']['GetInstalledApps']();
}

export function GetSessionFiles(arg1) {
  return window['go']['main']['App']['GetSessionFiles'](arg1);
}

export function GetSessionInfo(arg1) {
  return window['go']['main']['App']['GetSessionInfo'](arg1);
}

export function GetURLBlockerStatus() {
  return window['go']['main']['App']['GetURLBlockerStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InitDatabase() {
  return window['go']['main']['App']['InitDatabase']();
}

export function ListModes() {
  return window['go']['main']['App']['ListModes']();
}

export function PreviewCommand(arg1) {
  return window['go']['main']['App']['PreviewCommand'](arg1);
}

export function RunCommand(arg1) {
  return window['go']['main']['App']['RunCommand'](arg1);
}

export function SaveMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveMessage'](arg1, arg2, arg3);
}

export function ToggleMode(arg1, arg2) {
  return window['go']['main']['App']['ToggleMode'](arg1, arg2);
}

export function UpdateChatTitle(arg1, arg2) {
  return window['go']['main']['App']['UpdateChatTitle'](arg1, arg2);
}

export function UpdateMode(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['UpdateMode'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}
