// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateChat(arg1) {
  return window['go']['main']['App']['CreateChat'](arg1);
}

export function DeleteChat(arg1) {
  return window['go']['main']['App']['DeleteChat'](arg1);
}

export function ExecuteCommand(arg1, arg2) {
  return window['go']['main']['App']['ExecuteCommand'](arg1, arg2);
}

export function GetActiveChat() {
  return window['go']['main']['App']['GetActiveChat']();
}

export function GetChatMessages(arg1) {
  return window['go']['main']['App']['GetChatMessages'](arg1);
}

export function GetChats() {
  return window['go']['main']['App']['GetChats']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InitDatabase() {
  return window['go']['main']['App']['InitDatabase']();
}

export function PreviewCommand(arg1) {
  return window['go']['main']['App']['PreviewCommand'](arg1);
}

export function RunCommand(arg1) {
  return window['go']['main']['App']['RunCommand'](arg1);
}

export function SaveMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveMessage'](arg1, arg2, arg3);
}

export function UpdateChatTitle(arg1, arg2) {
  return window['go']['main']['App']['UpdateChatTitle'](arg1, arg2);
}
