// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExecuteCommand(arg1:string,arg2:boolean):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function PreviewCommand(arg1:string):Promise<main.CommandPreview>;

export function RunCommand(arg1:string):Promise<string>;
